---
title: "Statistiques"
author: "Marie Delacre"
fig_caption: yes
output:
  word_document: 
    reference_docx: draft-styles.docx
  pdf_document: default
figurelist: no
figsintext: yes
email: marie.delacre@ulb.ac.be
---

```{r setup, include=FALSE}
library(knitr)
library(bookdown)
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}

# Plan de travail
chap_intro="chapitre 1" # qu'est-ce que la stat, et à quoi ça sert?
chap_variables="chapitre 2" # catégorisation des variables
chap_graph="chapitre 3" # exploration graphique des données
chap_algebre="chapitre 4" # exploration algébrique des données
chap_distributions="chapitre 5" # les distributions binomiales et normales

# Table and Figure list

# Chapitre 1
table1_brut="Table 1.1" # Données brutes récoltées sur un échantillon de n employés belges du secteur                               #automobile" , utilise les données data1_brut

# Chapitre 3
fumeur_freq = "Table 3.1"
table3.1_brut= "Table 3.2"     # Données brutes correspondant au nombre d'enfants par ménage
table3.1_freq= "Table 3.3"     # Données transnumérisées correspondant au nombre d'enfants par ménage
fumeur_degres = "Table 3.4"  # degrés pour le diagramme circulaire
data3.1_degres="Table 3.5"

table3.2_freq="Table 3.6"      # PIB par habitant et par pays
table3.3_freq_a="Table 3.7"    # âge des habitants (catégories homogènes)
table3.3_freq_b="Table 3.8"    # âge des habitants (catégories non homogènes)

table3.4_brut="Table 3.9"
table3.5_brut="Table 3.10"

table3.6_serie1="Table 3.11"
table3.6_serie2="Table 3.12"
table3.6_serie3="Table 3.13"

table3.7="Table 3.14"

barplot_fumeur_freq="Figure 3.1"
pie_fumeur_freq="Figure 3.2"
barplot_data3.1_freq="Figure 3.3" # barplot des fréquences de la variable nombre d'enfants
pie_data3.1_freq="Figure 3.4"     # pie chart des fréquences de la variable nombre d'enfants
stair_data3.1_freq="Figure 3.5"   # diagramme en escalier des fréquences de la variable nombre d'enfants
barplot_data3.2_freq="Figure 3.6"  
barplot_data3.3_freq_a="Figure 3.7"   # diagramme en escalier des fréquences de la variable nombre d'enfants
barplot_data3.3_freq_b="Figure 3.8"   # diagramme en escalier des fréquences de la variable nombre d'enfants
polygone_data3.2_freq="Figure 3.9"  
polygone_data3.3_freq_a="Figure 3.10"   # diagramme en escalier des fréquences de la variable nombre d'enfants
polygone_data3.3_freq_b="Figure 3.11"   # diagramme en escalier des fréquences de la variable nombre d'enfants
boxplot_serie1="Figure 3.12"

# Chapitre 4
table4.1="Table 4.1" # extrait de la Table 1.1
table4.2="Table 4.2"  # extrait de la Table 1.1
notes_compta="Table 4.3" # données pour illustrer la variance
notes_ecart_math="Table 4.4"
notes_ecart_francais="Table 4.5"

Figure4.1="Figure 4.1"
```
```{r echo=FALSE, results='asis'}
Pays<-c("Luxembourg","Norvâge","Suisse","Irlande","Danemark","Suède","Pays-Bas","Islande","Autriche","Finlande","Allemagne","Belgique","Andorre","France","Royaume-Uni","Zone Euro","Union Européenne","Italie","Espagne","Chypre","Malte","Slovénie","Portugal","Grêce","République Tchèque","Slovaquie","Estonie","Lituanie","Pologne","Hongrie","Lettonie","Croatie","Turquie","Russie","Roumanie","Bulgarie","Monténégro","Biélorussie","Serbie","Bosnie-Herzégovine","Macédoine","Albanie","Kosovo","Ukraine","Moldavie")

PIB_hab<-c(107865.27,91218.62,76667.44,74433.46,61582.17,56935.19,53597.83,49910.01,49129.23,47057.62,46747.19,46078.93,43942.9,42567.74,42514.49,40088.65,36593.03,34877.83,32405.75,29432.67,27145.81,25662.41,23116.58,23027.41,22779.29,19897.15,18977.39,16793.25,15751.23,15647.85,15553.33,15219.88,14933.27,11441,10932.33,8311.93,7812.95,6375.82,5992.28,5561.29,5245.36,4868.2,4068.21,2991.63,2165.16)

mini=0
maxi=120000
nb_categ_PIB=6
categ_PIB=NULL
centre_PIB=NULL

for(j in 1:nb_categ_PIB){
  categ_PIB[j]=paste0("[",as.numeric((j-1)*(maxi-mini)/nb_categ_PIB),"-",as.numeric(j*(maxi-mini)/nb_categ_PIB),"[")  
  centre_PIB[j]=(as.numeric((j-1)*(maxi-mini)/nb_categ_PIB)+as.numeric(j*(maxi-mini)/nb_categ_PIB))/2
}

data3.2_brut=data.frame(Pays,PIB_hab)
```

```{r echo=FALSE, results='asis'}
abs_data3.2=NULL

for(i in 1:nb_categ_PIB){
  abs_data3.2[i]=sum((data3.2_brut$PIB_hab>=((i-1)*((maxi-mini)/nb_categ_PIB)))&(data3.2_brut$PIB_hab< (i*(maxi-mini)/nb_categ_PIB)))
}
rel_data3.2=abs_data3.2/sum(abs_data3.2)*100

abscum_data3.2=NULL
relcum_data3.2=NULL
count_abs_data3.2=0
count_rel_data3.2=0
for (i in 1:length(categ_PIB)){
  count_abs_data3.2=count_abs_data3.2+abs_data3.2[i]
  abscum_data3.2[i]=count_abs_data3.2
  count_rel_data3.2=count_rel_data3.2+rel_data3.2[i]
  relcum_data3.2[i]=count_rel_data3.2
}

data3.2_freq=data.frame(categ_PIB,centre_PIB,abs_data3.2,round(count_rel_data3.2,2),abscum_data3.2,round(relcum_data3.2,2)) 
```
 
`r polygone_data3.2_freq`  
_Histogramme de la distribution de la `r table3.2_freq` et polygone des effectifs_
```{r polygon_PIB, echo=FALSE}
par(mfrow=c(1,2),mar=c(4,2,2,2),xpd=TRUE)
amplitude=as.numeric((2)*(maxi-mini)/nb_categ_PIB)-as.numeric((1)*(maxi-mini)/nb_categ_PIB)

hist(data3.2_brut$PIB_hab,breaks=nb_categ_PIB,col="lightgrey",cex.main=.8,main="Histogramme de PIB",ylab="Fréquence absolue",cex.lab=1,xlab="PIB",las=2,cex.axis=.8,xlim=c(0,120000))
segments(centre_PIB[1]-(amplitude),0,centre_PIB[1],abs_data3.2[1],lwd=2)  
segments(centre_PIB[length(centre_PIB)],abs_data3.2[length(centre_PIB)],centre_PIB[length(centre_PIB)]+(amplitude),0,lwd=2)  
for(i in 1:(length(centre_PIB))){
segments(centre_PIB[i],abs_data3.2[i],centre_PIB[i+1],abs_data3.2[i+1],lwd=2)
points(centre_PIB[i],abs_data3.2[i],pch=16)
}

hist(data3.2_brut$PIB_hab,breaks=nb_categ_PIB,col="lightgrey",cex.main=.8,main="Histogramme de PIB",ylab="Fréquence relative",cex.lab=1,xlab="PIB",yaxt='n',las=2,cex.axis=.8,xlim=c(0,120000))
axis(2, at = seq(0,max(abs_data3.2),2), labels = round(seq(0,max(abs_data3.2),2)/sum(abs_data3.2),2),las = 2,cex.axis=.8)
segments(centre_PIB[1]-(amplitude),0,centre_PIB[1],abs_data3.2[1],lwd=2)  
segments(centre_PIB[length(centre_PIB)],abs_data3.2[length(centre_PIB)],centre_PIB[length(centre_PIB)]+(amplitude),0,lwd=2)  
for(i in 1:(length(centre_PIB))){
segments(centre_PIB[i],abs_data3.2[i],centre_PIB[i+1],abs_data3.2[i+1],lwd=2)  
points(centre_PIB[i],abs_data3.2[i],pch=16)
}
```